//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorAppDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        public int id_apoderado { get; set; }
        public string usuario { get; set; }
        public string mail { get; set; }
        public string telefono { get; set; }
        public string passwd { get; set; }
    
        public virtual apoderado apoderado { get; set; }
    }
}
