//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorAppDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntegracionEntities4 : DbContext
    {
        public IntegracionEntities4()
            : base("name=IntegracionEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apoderado> apoderado { get; set; }
        public virtual DbSet<comunas> comunas { get; set; }
        public virtual DbSet<last_location> last_location { get; set; }
        public virtual DbSet<portador> portador { get; set; }
        public virtual DbSet<provincias> provincias { get; set; }
        public virtual DbSet<regiones> regiones { get; set; }
        public virtual DbSet<registro_perdida> registro_perdida { get; set; }
    }
}
