//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorAppServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apoderado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public apoderado()
        {
            this.portador = new HashSet<portador>();
        }
    
        public int id_apoderado { get; set; }
        public string nombre { get; set; }
        public string apdpat { get; set; }
        public string apdmat { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string rut { get; set; }
        public string phone { get; set; }
        public string direccion { get; set; }
        public string membresia { get; set; }
        public int comuna_id { get; set; }
    
        public virtual comunas comunas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portador> portador { get; set; }
    }
}
