//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorAppServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comunas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comunas()
        {
            this.apoderado = new HashSet<apoderado>();
        }
    
        public int comuna_id { get; set; }
        public string comuna_nombre { get; set; }
        public int provincia_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apoderado> apoderado { get; set; }
        public virtual provincias provincias { get; set; }
    }
}
