//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorAppServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class last_location
    {
        public int id_perdida { get; set; }
        public Nullable<int> id_portador { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public Nullable<System.DateTime> hora_lectura { get; set; }
        public string ip_lectura { get; set; }
        public string auth_ip { get; set; }
        public string alerta_activa { get; set; }
    
        public virtual portador portador { get; set; }
    }
}
