//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorAppServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_perdida
    {
        public int id_registro { get; set; }
        public Nullable<int> id_portador { get; set; }
        public Nullable<int> id_apoderado { get; set; }
        public Nullable<System.DateTime> hora_perdida { get; set; }
        public string last_location { get; set; }
        public string detalles { get; set; }
        public byte[] imagen { get; set; }
        public byte[] estado_alerta { get; set; }
        public byte[] alerta_confirmada { get; set; }
        public byte[] enviado_auth { get; set; }
        public string ip_apoderado { get; set; }
    
        public virtual portador portador { get; set; }
    }
}
